<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="BADBOY" failures="1" tests="2" name="GroupTest" time="0.045" errors="0" timestamp="2022-02-26T11:54:59 IST">
  <testcase classname="TestNg.GroupTestExample" name="testPrintMessage" time="0.009"/>
  <testcase classname="TestNg.GroupTestExample" name="testingExitMessage" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [www..com] but found [www.tutorialspoint.com]">
      <![CDATA[java.lang.AssertionError: expected [www..com] but found [www.tutorialspoint.com]
at TestNg.GroupTestExample.testingExitMessage(GroupTestExample.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testingExitMessage -->
  <testcase classname="TestNg.GroupTestExample" name="testSalutationMessage" time="0.0">
    <ignored/>
  </testcase> <!-- testSalutationMessage -->
</testsuite> <!-- GroupTest -->
